openapi: 3.0.0
info:
  title: CovidNYTimes API Docs
  version: '1.0'
  description: 'API documentation for COVID-19 2020 cumulative counts of infection in the United States. Provided by the New York Times, based on data collected from state and local agencies. '
  contact:
    email: covid-data@nytimes.com
    name: Covid Data
  license:
    url: 'https://github.com/nytimes/covid-19-data/blob/master/LICENSE'
    name: License
servers:
  - url: 'https://covapi.herokuapp.com/'
    description: restapi
paths: {}
components:
  schemas: {}
