openapi: 3.0.0
info:
  title: CovidNYTimes API Docs
  version: '1.0'
  description: "API documentation for COVID-19 2020 cumulative counts of infection in the United States. Provided by the New York Times, based on data collected from state and local agencies.\n\nThe data begins with the first reported coronavirus case in Washington State on Jan. 21, 2020.\n\nCount of patients occurs at the place where they are treated, not where they live.\n\n**Confirmed**\nThis data reflects *Confirmed* cases. Cases are confirmed when they are reported by federal, state, territorial or local government agency. \n\n**Dates**\nEach date includes the cumulative count of cases or deaths reported on that day. \n"
  contact:
    email: covid-data@nytimes.com
    name: New York Times
    url: 'https://github.com/nytimes/covid-19-data'
  license:
    url: 'https://github.com/nytimes/covid-19-data/blob/master/LICENSE'
    name: License (CC BY-NC)
servers:
  - url: 'https://covapi.herokuapp.com/'
    description: restapi
paths:
  /api/timeline/states:
    get:
      summary: states
      tags:
        - states
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  state:
                    type: object
                    example: Alabama
                    description: Name of the State
                    properties:
                      date:
                        type: object
                        example: '2020-04-13'
                        description: Date in YYYY-MM-DD format
                        properties:
                          cases:
                            type: string
                            example: '10'
                            description: Number of cases in the state on the particular date
                          deaths:
                            type: string
                            description: Number of deaths in the state on a particular date.
                            example: '1'
              examples:
                example-1:
                  value:
                    Alabama:
                      '2020-04-13':
                        cases: '3805'
                        deaths: '104'
                      '2020-04-14':
                        cases: '3953'
                        deaths: '114'
                      '2020-04-15':
                        cases: '4241'
                        deaths: '123'
                      '2020-04-16':
                        cases: '4404'
                        deaths: '137'
                    Wyoming:
                      '2020-04-13':
                        cases: '275'
                        deaths: '1'
                      '2020-04-14':
                        cases: '282'
                        deaths: '1'
                      '2020-04-15':
                        cases: '288'
                        deaths: '2'
                      '2020-04-16':
                        cases: '296'
                        deaths: '2'
      operationId: get-api-timeline-states
      description: Gets a list broken out by state.
      parameters:
        - schema:
            type: string
            enum:
              - cases
              - deaths
            default: both
          in: query
          name: mode
          description: "Indicates if the counts of cases or the counts of deaths are desired.\n\nCan have 2 values `cases`, `deaths`. Default: both are  returned.\n "
        - schema:
            type: string
          in: query
    parameters: []
  '/api/timeline/states/{state}':
    parameters:
      - schema:
          type: string
        name: state
        in: path
        required: true
        description: Name of the state
    get:
      summary: '/states/{state}'
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: Timeline date in format YYYY-MM-DD.
                example: '2020-04-16'
                properties:
                  cases:
                    type: string
                    description: Count of the number of cases in the state on a particular date.
                    example: '120'
                  deaths:
                    type: string
                    description: Count of the number of deaths in the state on a particular date.
                    example: '1'
              examples:
                example-1:
                  value:
                    '2020-04-14':
                      cases: '3953'
                      deaths: '114'
                    '2020-04-15':
                      cases: '4241'
                      deaths: '123'
                    '2020-04-16':
                      cases: '4404'
                      deaths: '137'
      operationId: get-api-timeline-states-state
      description: 'Returns the timeline information for a single state. The state is specified as the Path Param. The timeline consists of information for each day, with a count of the number of COVID-19 cases in the state on that day and the count of the number of deaths in the state on that day.'
components:
  schemas: {}
